import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';
import StorageService, { StorageKeys } from '../utils/Storage';

const LocalizationContext = createContext({});

const translations = {
  en: {
    home: 'Home',
    favorites: 'Favorites',
    cart: 'Cart',
    settings: 'Settings',
    personal: 'Personal',
    profile: 'Profile',
    shippingAddress: 'Shipping Address',
    paymentMethods: 'Payment methods',
    shop: 'Shop',
    country: 'Country',
    currency: 'Currency',
    sizes: 'Sizes',
    terms: 'Terms and Conditions',
    account: 'Account',
    language: 'Language',
    aboutSlada: 'About Slada',
    deleteAccount: 'Delete My Account',
    yourProfile: 'Your Profile',
    saveChanges: 'Save Changes',
    name: 'Name',
    email: 'Email',
    password: 'Password',
    shippingAddressTitle: 'Shipping Address',
    chooseCountry: 'Choose your country',
    address: 'Address',
    townCity: 'Town / City',
    postcode: 'Postcode',
    phoneNumber: 'Phone Number',
    required: 'Required',
    myOrders: 'My Orders',
    stories: 'Stories',
    newItems: 'New Items',
    mostPopular: 'Most Popular',
    categories: 'Categories',
    flashSale: 'Flash Sale',
    topProducts: 'Top Products',
    justForYou: 'Just For You',
    recentlyViewed: 'Recently viewed',
    toPay: 'To Pay',
    toReceive: 'To Receive',
    toReview: 'To Review',
    seeAll: 'See All',
    announcement: 'Announcement',
    hello: 'Hello',
    chooseLanguage: 'Choose Language',
    english: 'English',
    amharic: 'Amharic',
    success: 'Success',
    error: 'Error',
    requiredMessage: 'Please fill all required fields.',
    shippingSaved: 'Shipping address saved.',
    profileSaved: 'Profile updated successfully.'
    ,
    searchProducts: 'Search products...',
    recentSearches: 'Recent Searches',
    recommendations: 'Recommendations',
    allCategories: 'All Categories',
    newLabel: 'New',
    saleLabel: 'Sale',
    hotLabel: 'Hot',
    allTab: 'All',
    femaleTab: 'Female',
    maleTab: 'Male',
    categoriesFilter: 'Categories Filter',
    clothing: 'Clothing',
    shoes: 'Shoes',
    bags: 'Bags',
    lingerie: 'Lingerie',
    accessories: 'Accessories',
    justForYouCategory: 'Just for You',
    wishlist: 'Wishlist',
    addedToCart: 'Added to Cart',
    addedToYourCart: 'added to your cart.',
    viewCart: 'View Cart',
    ok: 'OK',
    noWishlistItemsYet: 'No wishlist items yet',
    saveProductsToWishlist: 'Save products to wishlist and they will appear here.',
    exploreProducts: 'Explore Products',
    cartTitle: 'Cart',
    fromYourWishlist: 'From Your Wishlist',
    total: 'Total',
    checkout: 'Checkout',
    size: 'Size',
    color: 'Color',
    today: 'Today',
    yesterday: 'Yesterday',
    loremShort: 'Lorem ipsum dolor sit amet consectetur',
    loremLong: 'Lorem ipsum dolor sit amet consectetur.',
    clearAll: 'Clear All',
    discover: 'Discover',
    resultsFound: 'results found',
    noResultsFound: 'No results found',
    searchHint: 'Try checking your spelling or using different keywords',
    continue: 'Continue',
    addToCartText: 'Add to Cart',
    buyNow: 'Buy Now',
    selectSize: 'Select Size',
    selectColor: 'Select Color',
    moreImages: 'More Images',
    chooseYourDiscount: 'Choose Your Discount',
    live: 'Live',
    shopNow: 'Shop',
    aboutShoppeTitle: 'About Shoppe',
    aboutShoppeDescription: 'Shoppe - Shopping UI kit is likely a user interface (UI) kit designed to facilitate the development of e-commerce or shopping-related applications. UI kits are collections of pre-designed elements, components, and templates that developers and designers can use to create consistent and visually appealing user interfaces.',
    aboutShoppeSupport: 'If you need help or you have any questions, feel free to contact me by email.',
    aboutSladaDescription: 'Shoppe - Shopping UI kit is likely a user interface (UI) kit designed to facilitate the development of e-commerce or shopping-related applications. UI kits are collections of pre-designed elements, components, and templates that developers and designers can use to create consistent and visually appealing user interfaces.',
    aboutSladaSupport: 'If you need help or you have any questions, feel free to contact me by email.'
  },
  am: {
    home: 'መነሻ',
    favorites: 'ተወዳጆች',
    cart: 'ጋሪ',
    settings: 'ቅንብሮች',
    personal: 'የግል',
    profile: 'መገለጫ',
    shippingAddress: 'የመላኪያ አድራሻ',
    paymentMethods: 'የክፍያ መንገዶች',
    shop: 'ሱቅ',
    country: 'ሀገር',
    currency: 'ገንዘብ',
    sizes: 'መጠኖች',
    terms: 'ደንቦች እና ሁኔታዎች',
    account: 'መለያ',
    language: 'ቋንቋ',
    aboutSlada: 'ስለ ስላዳ',
    deleteAccount: 'መለያዬን ሰርዝ',
    yourProfile: 'መገለጫዎ',
    saveChanges: 'ለውጦችን አስቀምጥ',
    name: 'ስም',
    email: 'ኢሜይል',
    password: 'የይለፍ ቃል',
    shippingAddressTitle: 'የመላኪያ አድራሻ',
    chooseCountry: 'ሀገርዎን ይምረጡ',
    address: 'አድራሻ',
    townCity: 'ከተማ',
    postcode: 'ፖስታ ኮድ',
    phoneNumber: 'ስልክ ቁጥር',
    required: 'አስፈላጊ',
    myOrders: 'ትዕዛዞቼ',
    stories: 'ስቶሪዎች',
    newItems: 'አዲስ እቃዎች',
    mostPopular: 'ታዋቂዎች',
    categories: 'ምድቦች',
    flashSale: 'ፍላሽ ሽያጭ',
    topProducts: 'ከፍተኛ ምርቶች',
    justForYou: 'ለእርስዎ',
    recentlyViewed: 'በቅርቡ የታዩ',
    toPay: 'ለመክፈል',
    toReceive: 'ለመቀበል',
    toReview: 'ለመገምገም',
    seeAll: 'ሁሉን ይመልከቱ',
    announcement: 'ማስታወቂያ',
    hello: 'ሰላም',
    chooseLanguage: 'ቋንቋ ይምረጡ',
    english: 'እንግሊዝኛ',
    amharic: 'አማርኛ',
    success: 'ተሳክቷል',
    error: 'ስህተት',
    requiredMessage: 'እባክዎ አስፈላጊ መረጃዎችን ሁሉ ይሙሉ።',
    shippingSaved: 'የመላኪያ አድራሻ ተቀምጧል።',
    profileSaved: 'መገለጫው ተዘምኗል።',
    searchProducts: 'ምርቶችን ይፈልጉ...',
    recentSearches: 'የቅርብ ፍለጋዎች',
    recommendations: 'የተጠቆሙ',
    allCategories: 'ሁሉም ምድቦች',
    newLabel: 'አዲስ',
    saleLabel: 'ቅናሽ',
    hotLabel: 'ታዋቂ',
    allTab: 'ሁሉም',
    femaleTab: 'ሴቶች',
    maleTab: 'ወንዶች',
    categoriesFilter: 'የምድብ ማጣሪያ',
    clothing: 'ልብስ',
    shoes: 'ጫማ',
    bags: 'ቦርሳ',
    lingerie: 'የውስጥ ልብስ',
    accessories: 'አክሰሰሪ',
    justForYouCategory: 'ለእርስዎ ብቻ',
    wishlist: 'የተመኙት',
    addedToCart: 'ወደ ጋሪ ታክሏል',
    addedToYourCart: 'ወደ ጋሪዎ ታክሏል።',
    viewCart: 'ጋሪ ይመልከቱ',
    ok: 'እሺ',
    noWishlistItemsYet: 'እስካሁን የተመኙ እቃዎች የሉም',
    saveProductsToWishlist: 'ምርቶችን ወደ የተመኙት ያስቀምጡ እና እዚህ ይታያሉ።',
    exploreProducts: 'ምርቶችን ይመልከቱ',
    cartTitle: 'ጋሪ',
    fromYourWishlist: 'ከየተመኙት',
    total: 'ጠቅላላ',
    checkout: 'ክፍያ ይፈጽሙ',
    size: 'መጠን',
    color: 'ቀለም',
    today: 'ዛሬ',
    yesterday: 'ትናንት',
    loremShort: 'ለሙከራ የተጻፈ አጭር ጽሑፍ',
    loremLong: 'ለሙከራ የተጻፈ ጽሑፍ።',
    clearAll: 'ሁሉን አጥፋ',
    discover: 'ያግኙ',
    resultsFound: 'ውጤቶች ተገኝተዋል',
    noResultsFound: 'ውጤት አልተገኘም',
    searchHint: 'የጻፉትን ያረጋግጡ ወይም ሌላ ቃል ይጠቀሙ',
    continue: 'ቀጥል',
    addToCartText: 'ወደ ጋሪ ጨምር',
    buyNow: 'አሁን ግዛ',
    selectSize: 'መጠን ይምረጡ',
    selectColor: 'ቀለም ይምረጡ',
    moreImages: 'ተጨማሪ ምስሎች',
    chooseYourDiscount: 'ቅናሽዎን ይምረጡ',
    live: 'ቀጥታ',
    shopNow: 'ግዛ',
    aboutShoppeTitle: 'ስለ ሾፔ',
    aboutShoppeDescription: '"Shoppe - Shopping UI kit" የኢ-ኮሜርስ ወይም የግዢ መተግበሪያዎችን ለማበልጸግ የተዘጋጀ የተጠቃሚ መገናኛ (UI) ኪት ነው። UI ኪቶች አስቀድሞ የተዘጋጁ ንጥሎች፣ ኮምፖነንቶች እና አብነቶች ስብስብ ሲሆኑ አብራሪዎች እና ዲዛይነሮች ተመሳሳይ እና የሚስቡ የተጠቃሚ ቅጾችን ለመፍጠር ይጠቀሙባቸዋል።',
    aboutShoppeSupport: 'እርዳታ ከፈለጉ ወይም ጥያቄ ካለዎት በኢሜይል እባክዎ ያግኙኝ።',
    aboutSladaDescription: '"Shoppe - Shopping UI kit" የኢ-ኮሜርስ ወይም የግዢ መተግበሪያዎችን ለማበልጸግ የተዘጋጀ የተጠቃሚ መገናኛ (UI) ኪት ነው። UI ኪቶች አስቀድሞ የተዘጋጁ ንጥሎች፣ ኮምፖነንቶች እና አብነቶች ስብስብ ሲሆኑ አብራሪዎች እና ዲዛይነሮች ተመሳሳይ እና የሚስቡ የተጠቃሚ ቅጾችን ለመፍጠር ይጠቀሙባቸዋል።',
    aboutSladaSupport: 'እርዳታ ከፈለጉ ወይም ጥያቄ ካለዎት በኢሜይል እባክዎ ያግኙኝ።'
  }
};

export function LocalizationProvider({ children }) {
  const [language, setLanguage] = useState('en');

  useEffect(() => {
    const load = async () => {
      const prefs = await StorageService.getItem(StorageKeys.USER_PREFERENCES);
      if (prefs?.language) {
        setLanguage(prefs.language);
      }
    };
    load();
  }, []);

  const updateLanguage = async (nextLanguage) => {
    const safeLanguage = nextLanguage === 'am' ? 'am' : 'en';
    setLanguage(safeLanguage);
    const prefs = (await StorageService.getItem(StorageKeys.USER_PREFERENCES)) || {};
    await StorageService.setItem(StorageKeys.USER_PREFERENCES, { ...prefs, language: safeLanguage });
  };

  const t = (key, fallback = '') => translations[language]?.[key] || translations.en[key] || fallback || key;

  const value = useMemo(
    () => ({ language, setLanguage: updateLanguage, t }),
    [language]
  );

  return <LocalizationContext.Provider value={value}>{children}</LocalizationContext.Provider>;
}

export const useLocalization = () => useContext(LocalizationContext);
